//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IL_2.Air.Traffic.Controller.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Speech
    {
        public int id { get; set; }
        public string RecipientMessage { get; set; }
        public string NameSpeaker { get; set; }
        public string Message { get; set; }
        public string Lang { get; set; }
        public int Coalition { get; set; }
        public double Frequency { get; set; }
        public string Voice { get; set; }
        public double Speed { get; set; }
        public string Emotion { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
